### ISSUE TITLE
OpenVSP3Plugin on Linux.

### ISSUE THREAD

**Issue by FilipiKunz** [nasa/OpenVSP3Plugin#3]
Hi! I would like to understand about how I could install this plugin on linux

Thanks in advance.

**Comment by jfenbert** [comment]
Thanks for you interest in the OpenVSP3Plugin.
As described in the README.adoc file there is no installation required when running on linux.
Download the OpenVSP3Plugin.jar from the releases page.
Set the  OpenVSP_EXE environment variable to your OpenVSP executable's path and run the jar file. Assuming you have JAVA installed the command is:
java -jar OpenVSP3Plugin.jar
If you are still having problems please provide detailed information so that we can help.

**Comment by FilipiKunz** [comment]
I was able to install in Windows 7, it was difficult for me to put the local variables in Linux. Anyway, thanks for the help!

Another issue, I followed the initial step by step that was in the presentation that accompanies the program, but the program closed in the final step of the use. The same pointed to the correct path of OpenVSP3 and to the Java JDK. In addition, OpenMDAO was installed and tested with the default "Hello World".
